server:
  port: 8086

spring:
  cloud:
    stream:
      function:
        definition: inventoryEventProcessor;deliveryEventSubscriber
      bindings:
        inventoryEventProcessor-in-0:
          destination: status
        inventoryEventProcessor-out-0:
          destination: delivery
        deliveryEventSubscriber-in-0:
          destination: delivery
        deliveryEventSubscriber-out-0:
          destination: status
  application:
    name: delivery-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/delivery_db}
    username: ${DATABASE_USER:postgre_user}
    password: ${DATABASE_PASSWORD:postgre_secret_password}
    driver-class-name: org.postgresql.Driver
    maximum-pool-size: 100
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
    metrics:
      enabled: true

